version: '3.8'

services:

  lavalink:
    image: fredboat/lavalink
    container_name: lavalink
    restart: always
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml

  sunny:
    build: ./
    container_name: sunny
    volumes:
      - ./config.json:/home/appuser/config.json
    depends_on:
      - lavalink

networks:
  sunny:
